Provider, Resource, and DataSource types
hashicorp/terraform-plugin-framework pull request #32
Opened 2021-06-01 18:33 UTC by kmoe

closes #14
closes #15

2021-06-01 21:47 UTC, paddycarver requested changes
Some minor nitpicks and suggestions, but this looks pretty much right to me.

2021-06-01 21:47 UTC, paddycarver commented on provider.go
> +	GetSchema(context.Context) (*tfprotov6.Schema, []*tfprotov6.Diagnostic)
```suggestion
	GetSchema(context.Context) (schema.Schema, []*tfprotov6.Diagnostic)
```

2021-06-01 21:47 UTC, paddycarver commented on provider.go
> +type ProviderWithProviderMeta interface {
Should this inline the provider type, to be a superset of it?

```suggestion
type ProviderWithProviderMeta interface {
    Provider
```

2021-06-01 21:47 UTC, paddycarver commented on resource.go
> +// supports, it should instantiate a struct implementing ResourceType and return
```suggestion
// supports, it should define a type implementing ResourceType and return
```

2021-06-01 21:47 UTC, paddycarver commented on resource.go
> +	GetSchema(context.Context) (*tfprotov6.Schema, []*tfprotov6.Diagnostic)
```suggestion
	GetSchema(context.Context) (schema.Schema, []*tfprotov6.Diagnostic)
```

2021-06-02 11:17 UTC, kmoe commented on data_source.go
> +// provider supports, it should instantiate a struct implementing DataSourceType
If we clarify in this direction, I'd rather we change the whole thing to "it should define a type implementing DataSourceType and return an instance [of that type] in the map returned by Provider.GetDataSources." Will do so and we can see if it reads better.

2021-06-02 15:03 UTC, merged