Add Validate() to all collections
hashicorp/terraform-plugin-framework pull request #481
Opened 2022-09-14 05:10 UTC by Doridian

This also fixes a bug in `internal/reflect/map.go` where it used the map's own type to Validate elements, which does not seem correct at all.

2022-09-14 05:10 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-plugin-framework?pullRequest=481)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-plugin-framework?pullRequest=481)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-plugin-framework?pullRequest=481).</sub>

2022-09-14 14:09 UTC, bflad requested changes
Hi @Doridian 👋 Thank you for submitting this. Overall this is looking pretty good, it could just use some additional unit testing and small adjustments. If you have any questions about adding that testing, please reach out.

Also, if you could, it would be great to include a changelog entry which can be done by adding a `.changelog/481.txt` file with contents such as:

``````markdown
```release-note:bug
types: Ensured `List`, `Map`, and `Set` types with `xattr.TypeWithValidate` elements run validation on those elements
```
``````

2022-09-14 14:09 UTC, bflad commented on types/set.go
> +	validatableType, isValidatable := st.ElemType.(xattr.TypeWithValidate)
We should ensure there is a covering unit test for this change. 👍

2022-09-14 14:09 UTC, bflad commented on types/map.go
> +	if !in.Type().Is(tftypes.Map{}) {
We should ensure there is a covering unit test for this new conditional. 👍

2022-09-14 15:05 UTC, Doridian commented
It seems that `AtSetValue` expects an `attr.Value` which is not present in `Validate`. Pushed a fix for that.

2022-09-14 16:34 UTC, bflad commented
@Doridian since we are adding a method onto the type, we can unit test the method itself, e.g.

```go
func TestListTypeValidate(t *testing.T) {
	t.Parallel()

	testCases := map[string]struct {
		listType      ListType
		tfValue       tftypes.Value
		path          path.Path
		expectedDiags diag.Diagnostics
	}{
		"wrong-value-type": {
			listType: ListType{
				ElemType: StringType,
			},
			tfValue: tftypes.NewValue(tftypes.Set{
				ElementType: tftypes.String,
			}, []tftypes.Value{
				tftypes.NewValue(tftypes.String, "testvalue"),
			}),
			path: path.Root("test"),
			expectedDiags: diag.Diagnostics{
				diag.NewAttributeErrorDiagnostic(
					path.Root("test"),
					"List Type Validation Error",
					"An unexpected error was encountered trying to validate an attribute value. This is always an error in the provider. Please report the following to the provider developer:\n\n"+
						"expected List value, received tftypes.Value with value: tftypes.Set[tftypes.String]<tftypes.String<\"testvalue\">>",
				),
			},
		},
		"no-validation": {
			listType: ListType{
				ElemType: StringType,
			},
			tfValue: tftypes.NewValue(tftypes.List{
				ElementType: tftypes.String,
			}, []tftypes.Value{
				tftypes.NewValue(tftypes.String, "testvalue"),
			}),
			path: path.Root("test"),
		},
	}

	for name, testCase := range testCases {
		name, testCase := name, testCase

		t.Run(name, func(t *testing.T) {
			t.Parallel()

			diags := testCase.listType.Validate(context.Background(), testCase.tfValue, testCase.path)

			if diff := cmp.Diff(diags, testCase.expectedDiags); diff != "" {
				t.Errorf("unexpected diagnostics difference: %s", diff)
			}
		})
	}
}
```

Rinse and repeat for `MapType` and `SetType`.

This is okay for now as it would _unfortunately_ take a lot more effort to import the existing `internal/testing/types.StringTypeWithValidateError` to verify the element validation diagnostics are passed back, as importing that right now would cause an import cycle and updating the testing file to `package types_test` and putting `types.` in front of everything in the `types` package is a lot to ask. 😅

2022-09-14 16:46 UTC, bflad commented
(We could also create an unexported type with validation errors in the test files too, but it is totally fine.)

2022-09-15 00:02 UTC, Doridian commented
I have added tests for list and map exactly as you described.
For map, as it already was validatable, I have just appended the `wrong-value-type` test case.

2022-09-15 00:06 UTC, Doridian commented
> This is okay for now as it would _unfortunately_ take a lot more effort to import the existing `internal/testing/types.StringTypeWithValidateError` to verify the element validation diagnostics are passed back, as importing that right now would cause an import cycle and updating the testing file to `package types_test` and putting `types.` in front of everything in the `types` package is a lot to ask. 😅

Maybe in another PR if I find the time 😉

2022-09-15 13:13 UTC, bflad approved these changes
This looks great, @Doridian, thank you so much for your efforts here 🚀

2022-09-15 13:14 UTC, merged